name = "bg-remover-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
MAX_FILE_SIZE = "10485760"
ALLOWED_ORIGINS = "*"
REMOVEBG_API_KEY = "gS4kUV3WBuoc27rAHKQKtKR1"

[[kv_namespaces]]
binding = "USER_KV"
id = "9796916b1a204ad093ea4569b74754dd"

[env.production]
name = "bg-remover-worker"
